name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Puedes ajustar a tu rama principal
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub

env:
  AWS_REGION: us-east-1
  IMAGE_NAME: myapp

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read  # Necesario si usás OpenID Connect

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: echo "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Tag and Push to Amazon ECR
        run: |
          ECR_REPO="${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$IMAGE_NAME"
          docker tag $IMAGE_NAME:latest $ECR_REPO:latest
          docker push $ECR_REPO:latest

      - name: Tag and Push to Docker Hub
        run: |
          HUB_REPO="${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME"
          docker tag $IMAGE_NAME:latest $HUB_REPO:latest
          docker push $HUB_REPO:latest
