name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  IMAGE_NAME: myapp

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # --- Checkout code ---
      - name: Checkout code
        uses: actions/checkout@v3

      # --- Configure AWS credentials ---
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # --- Ensure ECR repository exists ---
      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names $IMAGE_NAME || \
          aws ecr create-repository --repository-name $IMAGE_NAME

      # --- Login to Amazon ECR ---
      - name: Login to Amazon ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      # --- Login to Docker Hub ---
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # --- Set Docker tag using commit SHA ---
      - name: Set Docker tag
        id: vars
        run: echo "TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      # --- Build Docker image ---
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest .

      # --- Tag and push to Amazon ECR ---
      - name: Tag and push to ECR
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}
          docker tag $IMAGE_NAME:latest $IMAGE_URI:latest
          docker tag $IMAGE_NAME:latest $IMAGE_URI:${{ steps.vars.outputs.TAG }}
          docker push $IMAGE_URI:latest
          docker push $IMAGE_URI:${{ steps.vars.outputs.TAG }}

      # --- Tag and push to Docker Hub ---
      - name: Tag and push to Docker Hub
        run: |
          docker tag $IMAGE_NAME:latest ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ steps.vars.outputs.TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ steps.vars.outputs.TAG }}
